### ISSUE TITLE
Product Requirements Document

### ISSUE THREAD

**Issue by Largent-Ethan** [rileyelwell/CS-GameDesignCompetition-23-24#4]
**Description**:
Complete the project documentation for our Product Requirements and have the entire group have a say and agree on it. It must reside in our documentation folder on our release branch as a Markdown file.
-- --
**Dependencies**:
- [x] #12  
-- --
**To-Do**:
- [ ] Problem Description
- [ ] Scope
- [ ] Use Cases
- [ ] Purpose and Vision
- [ ] Stakeholders
- [ ] Preliminary Contexts
- [ ] Market Assessment and Competition Analysis
- [ ] Target Demographics
- [ ] User Stories
- [ ] Non-Functional Requirements
- [ ] Data Requirements
- [ ] Integration Requirements
- [ ] User Interaction and Design
- [ ] Milestones and Timeline
- [ ] Goals and Success Metrics
- [ ] Open Questions
- [ ] Out of Scope
